### ISSUE TITLE
PHP 8.3 fatal error due to simple_html_dom

### ISSUE THREAD

**Issue by andrewcsp** [matdave/pageshrink#2]
I've noticed that the PageShrink doesn't work in PHP 8.3 due to an issue with the [simple_html_dom](https://github.com/voku/simple_html_dom) dependency noted here: https://github.com/voku/simple_html_dom/pull/110

The specific error I'm seeing is:
`PHP Fatal error:  Uncaught TypeError: Cannot assign null to property DOMElement::$id of type string in /home/<user>/<core>/components/pageshrink/model/vendor/voku/simple_html_dom/src/voku/helper/AbstractSimpleHtmlDom.php:174`

Running PHP 8.3.6 with MODX 2.8.7 and PageShrink 1.0.3

**Comment by matdave** [comment]
I've upgraded to the latest version of voku/simple_html_dom
